/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_slk_daemon_nativ_NativeDaemonAPI */

#ifndef _Included_com_slk_daemon_nativ_NativeDaemonAPI
#define _Included_com_slk_daemon_nativ_NativeDaemonAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_slk_daemon_nativ_NativeDaemonAPI
 * Method:    doDaemon20
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_slk_daemon_nativ_NativeDaemonAPI_doDaemon20
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_slk_daemon_nativ_NativeDaemonAPI
 * Method:    doDaemon21
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_slk_daemon_nativ_NativeDaemonAPI_doDaemon21
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
